apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis:8.0-M02-alpine3.20
      imagePullPolicy: IfNotPresent
      ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
  restartPolicy: Always
  