name: CD

on:
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Read version
        id: version
        run: echo "version=$(dotnet versionize inspect)" >> "$GITHUB_OUTPUT"
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_REGISTRY_USER }}
          password: ${{ secrets.DIGITALOCEAN_REGISTRY_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Build Dockerfile
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: ./src/Backend/Dockerfile
          push: true
          tags: registry.digitalocean.com/saveapis/mrbadexxcoaching-backend:${{ steps.version.outputs.version }}
          secrets: |
            "github_user=${{ github.actor }}"
            "github_token=${{ secrets.GITHUB_TOKEN }}"
            "hangfire_pro_url=${{ secrets.HANGFIRE_PRO_URL }}"
            "hangfire_pro_user=${{ secrets.HANGFIRE_PRO_USER }}"
            "hangfire_pro_token=${{ secrets.HANGFIRE_PRO_TOKEN }}"
            "hangfire_ace_url=${{ secrets.HANGFIRE_ACE_URL }}"
            "hangfire_ace_user=${{ secrets.HANGFIRE_ACE_USER }}"
            "hangfire_ace_token=${{ secrets.HANGFIRE_ACE_TOKEN }}"